// GENERATED by research/ts-sitter-spike/gen.ts from tree-sitter-json/src/parser.c. Do not edit.
import type { Lexer } from "./runtime.ts";
export const LANGUAGE_VERSION = 14;
export const SYMBOL_COUNT = 25;
export const TOKEN_COUNT = 15;
export const STATE_COUNT = 32;
export const LARGE_STATE_COUNT = 7;
export const symbolNames: string[] = ["end","{",",","}",":","[","]","\"","string_content","escape_sequence","number","true","false","null","comment","document","_value","object","pair","array","string","_string_content","document_repeat1","object_repeat1","array_repeat1"];
export const visible = new Uint8Array([0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,0,0,0,0]);
export const named = new Uint8Array([1,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0,0,0]);
export const parseTable = new Uint16Array([1,1,1,1,1,1,1,1,0,1,1,1,1,1,3,0,0,0,0,0,0,0,0,0,0,5,7,0,0,0,9,0,11,0,0,13,13,13,13,3,30,2,8,0,8,8,0,2,0,0,15,7,0,0,0,9,0,11,0,0,13,13,13,13,3,0,3,8,0,8,8,0,3,0,0,17,19,0,0,0,22,0,25,0,0,28,28,28,28,3,0,3,8,0,8,8,0,3,0,0,0,7,0,0,0,9,31,11,0,0,13,13,13,13,3,0,21,8,0,8,8,0,0,0,0,33,33,33,33,33,33,33,33,0,0,33,33,33,33,3,0,0,0,0,0,0,0,0,0,0,35,35,35,35,35,35,35,35,0,0,35,35,35,35,3,0,0,0,0,0,0,0,0,0,0]);
export const smallTable = new Uint16Array([2,3,1,14,37,11,0,1,2,3,5,6,7,10,11,12,13,2,3,1,14,39,11,0,1,2,3,5,6,7,10,11,12,13,2,3,1,14,41,11,0,1,2,3,5,6,7,10,11,12,13,7,3,1,14,7,1,1,9,1,5,11,1,7,29,1,16,8,3,17,19,20,13,4,10,11,12,13,2,3,1,14,43,11,0,1,2,3,5,6,7,10,11,12,13,2,3,1,14,45,11,0,1,2,3,5,6,7,10,11,12,13,7,3,1,14,7,1,1,9,1,5,11,1,7,28,1,16,8,3,17,19,20,13,4,10,11,12,13,2,3,1,14,47,11,0,1,2,3,5,6,7,10,11,12,13,2,3,1,14,49,11,0,1,2,3,5,6,7,10,11,12,13,5,3,1,14,11,1,7,51,1,3,20,1,18,31,1,20,4,53,1,7,57,1,14,18,1,21,55,2,8,9,4,57,1,14,59,1,7,19,1,21,61,2,8,9,4,57,1,14,63,1,7,19,1,21,65,2,8,9,4,3,1,14,68,1,2,70,1,3,22,1,23,4,3,1,14,72,1,2,74,1,6,24,1,24,4,3,1,14,68,1,2,76,1,3,25,1,23,4,3,1,14,11,1,7,27,1,18,31,1,20,4,3,1,14,72,1,2,78,1,6,26,1,24,4,3,1,14,80,1,2,83,1,3,25,1,23,4,3,1,14,85,1,2,88,1,6,26,1,24,2,3,1,14,83,2,2,3,2,3,1,14,90,2,2,3,2,3,1,14,88,2,2,6,2,3,1,14,92,1,0,2,3,1,14,94,1,4]);
export const smallMap = new Uint32Array([0,17,34,51,78,95,112,139,156,173,189,203,217,231,244,257,270,283,296,309,322,330,338,346,353]);
export const actions = new Int32Array([0,0,0,0,0,0,0,0,4,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,2,15,0,0,0,0,0,0,1,16,0,0,0,0,0,0,1,4,0,0,0,0,0,0,1,17,0,0,0,0,0,0,1,8,0,0,0,0,0,0,2,15,1,0,0,0,0,0,2,22,2,0,0,0,0,0,2,22,2,0,1,16,2,0,0,0,0,0,2,22,2,0,1,4,2,0,0,0,0,0,2,22,2,0,1,17,2,0,0,0,0,0,2,22,2,0,1,8,2,0,0,0,0,0,1,9,0,0,0,0,0,0,2,20,2,0,0,0,0,0,2,20,3,0,0,0,0,0,2,17,2,0,0,0,0,0,2,16,1,0,0,0,0,0,2,19,2,0,0,0,0,0,2,17,3,0,0,0,0,0,2,17,4,0,0,0,0,0,2,19,3,0,0,0,0,0,2,19,4,0,0,0,0,0,1,7,0,0,0,0,0,0,1,5,0,0,0,0,0,0,1,18,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,6,0,0,0,0,0,0,1,19,0,0,0,0,0,0,2,21,2,0,0,0,0,0,2,21,2,0,1,19,2,0,0,0,0,0,1,23,0,0,0,0,0,0,1,11,0,0,0,0,0,0,1,10,0,0,0,0,0,0,1,14,0,0,0,0,0,0,1,12,0,0,0,0,0,0,1,15,0,0,0,0,0,0,2,23,2,0,1,23,2,0,0,0,0,0,2,23,2,0,0,0,0,0,2,24,2,0,1,10,2,0,0,0,0,0,2,24,2,0,0,0,0,0,2,18,3,1,0,0,0,0,3,0,0,0,0,0,0,0,1,13,0,0]);
export const actionCount = new Uint8Array([0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,2,0,0,2,0,0,2,0,0,2,0,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,2,0,0,1,0,1,0,1,0,1,0,1,0,1,0,2,0,0,1,0,2,0,0,1,0,1,0,1,0,1,0]);
export const lexModes = new Uint16Array([0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0]);
export function lex(L: Lexer, state: number): boolean {
  let result = false, skip = false, first = true;
  for (;;) {
    if (first) first = false; else L.advance(skip);
    skip = false;
    const lookahead = L.lookahead;
    const eof = L.pos >= L.end;

  
  
  switch (state) {
    case 0:
      if (eof) { state = 21; continue; }
      switch (lookahead) { case 34: state = 28; continue; case 44: state = 23; continue; case 45: state = 7; continue; case 47: state = 3; continue; case 48: state = 35; continue; case 58: state = 25; continue; case 91: state = 26; continue; case 92: state = 18; continue; case 93: state = 27; continue; case 102: state = 8; continue; case 110: state = 17; continue; case 116: state = 14; continue; case 123: state = 22; continue; case 125: state = 24; continue; }
      if ((9 <= lookahead && lookahead <= 13) ||
          lookahead == 32) { skip = true; state = 20; continue; }
      if ((49 <= lookahead && lookahead <= 57)) { state = 36; continue; }
      return result;
    case 1:
      if (lookahead == 10) { skip = true; state = 2; continue; }
      if (lookahead == 34) { state = 28; continue; }
      if (lookahead == 47) { state = 29; continue; }
      if (lookahead == 92) { state = 18; continue; }
      if ((9 <= lookahead && lookahead <= 13) ||
          lookahead == 32) { state = 32; continue; }
      if (lookahead != 0) { state = 33; continue; }
      return result;
    case 2:
      if (lookahead == 34) { state = 28; continue; }
      if (lookahead == 47) { state = 3; continue; }
      if ((9 <= lookahead && lookahead <= 13) ||
          lookahead == 32) { skip = true; state = 2; continue; }
      return result;
    case 3:
      if (lookahead == 42) { state = 5; continue; }
      if (lookahead == 47) { state = 43; continue; }
      return result;
    case 4:
      if (lookahead == 42) { state = 4; continue; }
      if (lookahead == 47) { state = 42; continue; }
      if (lookahead != 0) { state = 5; continue; }
      return result;
    case 5:
      if (lookahead == 42) { state = 4; continue; }
      if (lookahead != 0) { state = 5; continue; }
      return result;
    case 6:
      if (lookahead == 45) { state = 19; continue; }
      if ((48 <= lookahead && lookahead <= 57)) { state = 38; continue; }
      return result;
    case 7:
      if (lookahead == 48) { state = 35; continue; }
      if ((49 <= lookahead && lookahead <= 57)) { state = 36; continue; }
      return result;
    case 8:
      if (lookahead == 97) { state = 11; continue; }
      return result;
    case 9:
      if (lookahead == 101) { state = 39; continue; }
      return result;
    case 10:
      if (lookahead == 101) { state = 40; continue; }
      return result;
    case 11:
      if (lookahead == 108) { state = 15; continue; }
      return result;
    case 12:
      if (lookahead == 108) { state = 41; continue; }
      return result;
    case 13:
      if (lookahead == 108) { state = 12; continue; }
      return result;
    case 14:
      if (lookahead == 114) { state = 16; continue; }
      return result;
    case 15:
      if (lookahead == 115) { state = 10; continue; }
      return result;
    case 16:
      if (lookahead == 117) { state = 9; continue; }
      return result;
    case 17:
      if (lookahead == 117) { state = 13; continue; }
      return result;
    case 18:
      switch (lookahead) { case 34: state = 34; continue; case 47: state = 34; continue; case 92: state = 34; continue; case 98: state = 34; continue; case 102: state = 34; continue; case 110: state = 34; continue; case 114: state = 34; continue; case 116: state = 34; continue; case 117: state = 34; continue; }
      return result;
    case 19:
      if ((48 <= lookahead && lookahead <= 57)) { state = 38; continue; }
      return result;
    case 20:
      if (eof) { state = 21; continue; }
      switch (lookahead) { case 34: state = 28; continue; case 44: state = 23; continue; case 45: state = 7; continue; case 47: state = 3; continue; case 48: state = 35; continue; case 58: state = 25; continue; case 91: state = 26; continue; case 93: state = 27; continue; case 102: state = 8; continue; case 110: state = 17; continue; case 116: state = 14; continue; case 123: state = 22; continue; case 125: state = 24; continue; }
      if ((9 <= lookahead && lookahead <= 13) ||
          lookahead == 32) { skip = true; state = 20; continue; }
      if ((49 <= lookahead && lookahead <= 57)) { state = 36; continue; }
      return result;
    case 21:
      result = true; L.resultSymbol = 0; L.tokenEnd = L.pos;
      return result;
    case 22:
      result = true; L.resultSymbol = 1; L.tokenEnd = L.pos;
      return result;
    case 23:
      result = true; L.resultSymbol = 2; L.tokenEnd = L.pos;
      return result;
    case 24:
      result = true; L.resultSymbol = 3; L.tokenEnd = L.pos;
      return result;
    case 25:
      result = true; L.resultSymbol = 4; L.tokenEnd = L.pos;
      return result;
    case 26:
      result = true; L.resultSymbol = 5; L.tokenEnd = L.pos;
      return result;
    case 27:
      result = true; L.resultSymbol = 6; L.tokenEnd = L.pos;
      return result;
    case 28:
      result = true; L.resultSymbol = 7; L.tokenEnd = L.pos;
      return result;
    case 29:
      result = true; L.resultSymbol = 8; L.tokenEnd = L.pos;
      if (lookahead == 42) { state = 31; continue; }
      if (lookahead == 47) { state = 33; continue; }
      if (lookahead != 0 &&
          lookahead != 10 &&
          lookahead != 34 &&
          lookahead != 92) { state = 33; continue; }
      return result;
    case 30:
      result = true; L.resultSymbol = 8; L.tokenEnd = L.pos;
      if (lookahead == 42) { state = 30; continue; }
      if (lookahead == 47) { state = 33; continue; }
      if (lookahead != 0 &&
          lookahead != 10 &&
          lookahead != 34 &&
          lookahead != 92) { state = 31; continue; }
      return result;
    case 31:
      result = true; L.resultSymbol = 8; L.tokenEnd = L.pos;
      if (lookahead == 42) { state = 30; continue; }
      if (lookahead != 0 &&
          lookahead != 10 &&
          lookahead != 34 &&
          lookahead != 92) { state = 31; continue; }
      return result;
    case 32:
      result = true; L.resultSymbol = 8; L.tokenEnd = L.pos;
      if (lookahead == 47) { state = 29; continue; }
      if (lookahead == 9 ||
          (0x0b <= lookahead && lookahead <= 13) ||
          lookahead == 32) { state = 32; continue; }
      if (lookahead != 0 &&
          (lookahead < 9 || 13 < lookahead) &&
          lookahead != 34 &&
          lookahead != 92) { state = 33; continue; }
      return result;
    case 33:
      result = true; L.resultSymbol = 8; L.tokenEnd = L.pos;
      if (lookahead != 0 &&
          lookahead != 10 &&
          lookahead != 34 &&
          lookahead != 92) { state = 33; continue; }
      return result;
    case 34:
      result = true; L.resultSymbol = 9; L.tokenEnd = L.pos;
      return result;
    case 35:
      result = true; L.resultSymbol = 10; L.tokenEnd = L.pos;
      if (lookahead == 46) { state = 37; continue; }
      if (lookahead == 69 ||
          lookahead == 101) { state = 6; continue; }
      return result;
    case 36:
      result = true; L.resultSymbol = 10; L.tokenEnd = L.pos;
      if (lookahead == 46) { state = 37; continue; }
      if (lookahead == 69 ||
          lookahead == 101) { state = 6; continue; }
      if ((48 <= lookahead && lookahead <= 57)) { state = 36; continue; }
      return result;
    case 37:
      result = true; L.resultSymbol = 10; L.tokenEnd = L.pos;
      if (lookahead == 69 ||
          lookahead == 101) { state = 6; continue; }
      if ((48 <= lookahead && lookahead <= 57)) { state = 37; continue; }
      return result;
    case 38:
      result = true; L.resultSymbol = 10; L.tokenEnd = L.pos;
      if ((48 <= lookahead && lookahead <= 57)) { state = 38; continue; }
      return result;
    case 39:
      result = true; L.resultSymbol = 11; L.tokenEnd = L.pos;
      return result;
    case 40:
      result = true; L.resultSymbol = 12; L.tokenEnd = L.pos;
      return result;
    case 41:
      result = true; L.resultSymbol = 13; L.tokenEnd = L.pos;
      return result;
    case 42:
      result = true; L.resultSymbol = 14; L.tokenEnd = L.pos;
      return result;
    case 43:
      result = true; L.resultSymbol = 14; L.tokenEnd = L.pos;
      if (lookahead != 0 &&
          lookahead != 10) { state = 43; continue; }
      return result;
    default:
      return false;
  }

  }
}
