// Writes src/<lang>/grammar.ts from a tree-sitter grammar's node-types.json and grammar.json, so rule tables are
// typed by the parser's actual vocabulary. Run:
//   node src/gen-grammar.node.ts json tree-sitter-json --comments comment
//   node src/gen-grammar.node.ts typescript tree-sitter-typescript/typescript --comments comment
// The grammar is `<package>[/<subdirectory>]`: some packages keep several grammars, each in its own src/.
// Comment kinds are named, not derived: a grammar's extras also hold kinds that are not comments (Python's
// `line_continuation`, TypeScript's `html_comment`), and a comment kind printed as code would lose its text.
import { mkdirSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { parseArgs } from "node:util";

const {
  positionals: [lang, grammarPath],
  values,
} = parseArgs({
  allowPositionals: true,
  options: { comments: { type: "string" } },
});
if (!lang || !grammarPath || values.comments === undefined)
  throw new Error(
    "usage: gen-grammar.node.ts <lang> <package>[/<subdirectory>] --comments <kind>[,<kind>...]",
  );
const segments = grammarPath.split("/");
const pkgLength = grammarPath.startsWith("@") ? 2 : 1;
const pkg = segments.slice(0, pkgLength).join("/");
const dir = segments.slice(pkgLength).join("/");
const src = dir ? `${pkg}/${dir}/src` : `${pkg}/src`;

// The grammar packages are the engine's dependencies; this package only reads them.
const require = createRequire(
  new URL("../../engine/package.json", import.meta.url),
);
const nodeTypes: {
  type: string;
  named: boolean;
  subtypes?: unknown;
  fields?: Record<string, unknown>;
}[] = require(`${src}/node-types.json`);
const { extras }: { extras: { type: string; name?: string }[] } = require(
  `${src}/grammar.json`,
);
const version: string = require(`${pkg}/package.json`).version;

const sorted = (xs: Iterable<string>) => [...new Set(xs)].sort();
const kinds = sorted(
  nodeTypes.filter((t) => t.named && !t.subtypes).map((t) => t.type),
);
const extraKinds = new Set(
  extras.flatMap((e) => (e.type === "SYMBOL" && e.name ? [e.name] : [])),
);
const comments = sorted(values.comments.split(",").filter(Boolean));
for (const c of comments)
  if (!extraKinds.has(c))
    throw new Error(
      `${c} is not an extra of ${grammarPath}, so the parser cannot place it anywhere; its extras are ${[...extraKinds].join(", ")}`,
    );

const grammar = {
  kinds,
  tokens: sorted(nodeTypes.filter((t) => !t.named).map((t) => t.type)),
  fields: sorted(nodeTypes.flatMap((t) => Object.keys(t.fields ?? {}))),
  comments,
};

const outDir = new URL(`./${lang}/`, import.meta.url);
mkdirSync(outDir, { recursive: true });
const out = new URL("grammar.ts", outDir);
writeFileSync(
  out,
  `// Generated by src/gen-grammar.node.ts from ${grammarPath} (${pkg} ${version}). Do not edit.
export const grammar = ${JSON.stringify(grammar, null, 2)} as const;
`,
);
console.log(`wrote ${out.pathname}`);
