// Writes src/<lang>/grammar.ts from a tree-sitter grammar package's node-types.json and grammar.json, so rule
// tables are typed by the parser's actual vocabulary. Run: node src/gen-grammar.node.ts json tree-sitter-json
import { writeFileSync } from "node:fs";
import { createRequire } from "node:module";

const [lang, pkg] = process.argv.slice(2);
if (!lang || !pkg)
  throw new Error("usage: gen-grammar.node.ts <lang> <tree-sitter package>");

// The grammar packages are the engine's dependencies; this package only reads them.
const require = createRequire(
  new URL("../../engine/package.json", import.meta.url),
);
const nodeTypes: {
  type: string;
  named: boolean;
  subtypes?: unknown;
  fields?: Record<string, unknown>;
}[] = require(`${pkg}/src/node-types.json`);
const { extras }: { extras: { type: string; name?: string }[] } = require(
  `${pkg}/src/grammar.json`,
);
const version: string = require(`${pkg}/package.json`).version;

const sorted = (xs: Iterable<string>) => [...new Set(xs)].sort();
const grammar = {
  kinds: sorted(
    nodeTypes.filter((t) => t.named && !t.subtypes).map((t) => t.type),
  ),
  tokens: sorted(nodeTypes.filter((t) => !t.named).map((t) => t.type)),
  fields: sorted(nodeTypes.flatMap((t) => Object.keys(t.fields ?? {}))),
  comments: sorted(
    extras.flatMap((e) => (e.type === "SYMBOL" && e.name ? [e.name] : [])),
  ),
};

const out = new URL(`./${lang}/grammar.ts`, import.meta.url);
writeFileSync(
  out,
  `// Generated by src/gen-grammar.node.ts from ${pkg} ${version}. Do not edit.
export const grammar = ${JSON.stringify(grammar, null, 2)} as const;
`,
);
console.log(`wrote ${out.pathname}`);
