// Swift's layout in the formatter DSL (src/fmt/dsl/dsl.ts), as swift-format 6.3.0 prints it; `pnpm generate`
// compiles it into fmt.gen.ts. The formatter does not lay Swift out yet: fmt.ts refuses a file whose layout
// swift-format would change, so every kind keeps its children as written (`written`), and a statement swift-format
// re-lays past the width prints as fmt.ts's port of its printer lays it out (`laidOut`).
import { custom, defineFormat, either, inOrder, verbatim, when } from "../../fmt/dsl/dsl.js";
import type { grammar } from "./bundle.js";
import type { SwiftOptions } from "./fmt.js";

const format = defineFormat<typeof grammar, SwiftOptions>();

/**
 * The children as the source separates them, but for the tokens fmt.ts finds swift-format's rules change. Where fmt.ts finds the file's `#if` bodies flush with their
 * directives (as Xcode writes them), each body goes a level in, as swift-format indents it.
 */
const written = inOrder({
  join: "written",
  nest: {
    kind: "directive",
    opens: ["#if", "#elseif", "#else"],
    closes: ["#elseif", "#else", "#endif"],
    when: when("flushConditionals"),
  },
  // The tokens swift-format's rules drop or add a keyword before (fmt.ts: an extension's access level moved onto
  // its members, a case pattern's `let` onto each binding).
  edit: "tokenEdit",
});
/** A statement fmt.ts lays out (pretty.ts's printer, through the body's `{`), else as written. */
const statement = () => either(when("laidOut"), custom("layOut"), written);
// Any node may be one fmt.ts lays out: a dictionary element's key, say, as well as a statement.
const keep = () => statement();
const token = () => verbatim;

export const swift = format({
  structure: {
    source_file: keep,
    statements: keep,
    directive: keep,
    shebang_line: token,
    comment: token,
    multiline_comment: token,
    diagnostic: token,

    // Declarations.
    import_declaration: keep,
    property_declaration: statement,
    function_declaration: statement,
    init_declaration: statement,
    deinit_declaration: keep,
    subscript_declaration: keep,
    class_declaration: keep,
    class_body: keep,
    enum_class_body: keep,
    enum_entry: keep,
    enum_type_parameters: keep,
    protocol_declaration: keep,
    protocol_body: keep,
    protocol_function_declaration: keep,
    protocol_property_declaration: keep,
    protocol_property_requirements: keep,
    typealias_declaration: keep,
    associatedtype_declaration: keep,
    operator_declaration: keep,
    deprecated_operator_declaration_body: keep,
    precedence_group_declaration: keep,
    precedence_group_attributes: keep,
    precedence_group_attribute: keep,
    macro_declaration: keep,
    macro_definition: keep,
    external_macro_definition: keep,
    function_body: keep,
    parameter: keep,
    computed_property: keep,
    computed_getter: keep,
    computed_setter: keep,
    computed_modify: keep,
    getter_specifier: keep,
    setter_specifier: keep,
    modify_specifier: keep,
    willset_didset_block: keep,
    willset_clause: keep,
    didset_clause: keep,
    inheritance_specifier: keep,
    throws_clause: keep,

    // Modifiers and attributes.
    modifiers: keep,
    attribute: keep,
    visibility_modifier: keep,
    member_modifier: keep,
    mutation_modifier: keep,
    property_modifier: keep,
    parameter_modifier: keep,
    parameter_modifiers: keep,
    inheritance_modifier: keep,
    ownership_modifier: keep,
    property_behavior_modifier: keep,
    function_modifier: keep,
    type_modifiers: keep,
    type_parameter_modifiers: keep,
    throws: token,

    // Statements.
    if_statement: statement,
    guard_statement: statement,
    while_statement: statement,
    control_transfer_statement: statement,
    assignment: statement,
    for_statement: keep,
    repeat_while_statement: keep,
    do_statement: keep,
    catch_block: keep,
    switch_statement: keep,
    switch_entry: keep,
    switch_pattern: keep,
    discard_statement: keep,
    availability_condition: keep,
    statement_label: token,
    else: token,
    catch_keyword: token,
    default_keyword: token,
    throw_keyword: token,
    where_keyword: token,
    where_clause: keep,

    // Expressions.
    call_expression: statement,
    try_expression: statement,
    _expression: keep,
    call_suffix: keep,
    value_arguments: keep,
    value_argument: keep,
    value_argument_label: keep,
    constructor_expression: keep,
    constructor_suffix: keep,
    navigation_expression: keep,
    navigation_suffix: keep,
    directly_assignable_expression: keep,
    postfix_expression: keep,
    prefix_expression: keep,
    as_expression: keep,
    as_operator: keep,
    check_expression: keep,
    try_operator: keep,
    await_expression: keep,
    consume_expression: keep,
    additive_expression: keep,
    multiplicative_expression: keep,
    comparison_expression: keep,
    equality_expression: keep,
    conjunction_expression: keep,
    disjunction_expression: keep,
    nil_coalescing_expression: keep,
    infix_expression: keep,
    bitwise_operation: keep,
    ternary_expression: keep,
    range_expression: keep,
    open_start_range_expression: keep,
    open_end_range_expression: keep,
    fully_open_range: keep,
    tuple_expression: keep,
    self_expression: keep,
    super_expression: keep,
    key_path_expression: keep,
    key_path_string_expression: keep,
    selector_expression: keep,
    macro_invocation: keep,
    value_pack_expansion: keep,
    value_parameter_pack: keep,
    lambda_literal: keep,
    lambda_function_type: keep,
    lambda_function_type_parameters: keep,
    lambda_parameter: keep,
    capture_list: keep,
    capture_list_item: keep,
    custom_operator: token,
    bang: keep,

    // Literals.
    array_literal: keep,
    dictionary_literal: keep,
    boolean_literal: keep,
    integer_literal: token,
    hex_literal: token,
    bin_literal: token,
    oct_literal: token,
    real_literal: token,
    special_literal: token,
    playground_literal: keep,
    regex_literal: token,
    line_string_literal: keep,
    multi_line_string_literal: keep,
    raw_string_literal: keep,
    interpolated_expression: keep,
    raw_str_interpolation: keep,
    line_str_text: token,
    multi_line_str_text: token,
    str_escaped_char: token, // `\u{...}`'s braces and digits are no tokens of their own
    raw_str_part: token,
    raw_str_end_part: token,
    raw_str_continuing_indicator: token,
    raw_str_interpolation_start: token,

    // Names and patterns.
    simple_identifier: keep,
    identifier: keep,
    pattern: keep,
    value_binding_pattern: keep,
    wildcard_pattern: token,

    // Types.
    user_type: keep,
    type_identifier: token,
    type_annotation: keep,
    type_arguments: keep,
    type_parameters: keep,
    type_parameter: keep,
    type_parameter_pack: keep,
    type_pack_expansion: keep,
    type_constraints: keep,
    type_constraint: keep,
    inheritance_constraint: keep,
    equality_constraint: keep,
    suppressed_constraint: keep,
    array_type: keep,
    dictionary_type: keep,
    optional_type: keep,
    tuple_type: keep,
    tuple_type_item: keep,
    function_type: keep,
    metatype: keep,
    opaque_type: keep,
    existential_type: keep,
    protocol_composition_type: keep,
    bracket_qualified_type: keep,
  },
});
