// musl's <wctype.h>, read straight out of web-tree-sitter.wasm: the grammar wasm modules import iswalpha,
// iswspace and iswalnum from it, so its answers are the ones the C scanners see. Running this file writes
// src/core/musl-alpha.ts, the iswalpha set as sorted inclusive ranges for `setContains`.
// Run after `pnpm typecheck`: node packages/syntechs/dist/core/wctype.node.js
import { readFileSync, writeFileSync } from "node:fs";
import { createRequire } from "node:module";
import { join, resolve } from "node:path";

export const MAX_CODE_POINT = 0x10ffff;

export interface MuslWctype {
  iswalpha(c: number): number;
  iswalnum(c: number): number;
  iswdigit(c: number): number;
  iswspace(c: number): number;
}

// The compiler options load no WebAssembly lib (the runtime never touches wasm), so this probe types the few calls it makes.
interface Wasm {
  Module: {
    new (bytes: Uint8Array): object;
    imports(m: object): { module: string; name: string; kind: string }[];
  };
  Instance: new (m: object, imports: object) => { exports: unknown };
  Memory: new (d: { initial: number; maximum: number }) => object;
  Table: new (d: { initial: number; element: string }) => object;
  Global: new (d: { value: string; mutable: boolean }, v: number) => object;
}
const WebAssembly = (globalThis as unknown as { WebAssembly: Wasm })
  .WebAssembly;

/** Instantiates the runtime wasm on its own; the wctype exports only read static tables, so every other import is a stub. */
export function loadMuslWctype(): MuslWctype {
  const path = createRequire(import.meta.url).resolve(
    "web-tree-sitter/web-tree-sitter.wasm",
  );
  const module = new WebAssembly.Module(readFileSync(path));
  const i32 = (value: number, mutable = false) =>
    new WebAssembly.Global({ value: "i32", mutable }, value);
  const imports: Record<string, Record<string, unknown>> = {
    env: {
      memory: new WebAssembly.Memory({ initial: 512, maximum: 32768 }),
      __indirect_function_table: new WebAssembly.Table({
        initial: 4096,
        element: "anyfunc",
      }),
      __stack_pointer: i32(8 << 20, true),
      __memory_base: i32(1024),
      __table_base: i32(1),
    },
    "GOT.mem": {
      __stack_low: i32(4 << 20, true),
      __stack_high: i32(8 << 20, true),
      __heap_base: i32(16 << 20, true),
    },
  };
  for (const imp of WebAssembly.Module.imports(module)) {
    if (imp.kind !== "function") continue;
    imports[imp.module] = {
      ...imports[imp.module],
      [imp.name]: () => {
        throw new Error(`wctype probe called ${imp.module}.${imp.name}`);
      },
    };
  }
  const exports = new WebAssembly.Instance(module, imports)
    .exports as unknown as MuslWctype & { __wasm_apply_data_relocs(): void };
  exports.__wasm_apply_data_relocs();
  return exports;
}

function main(): void {
  const musl = loadMuslWctype();
  const ranges: number[] = [];
  for (let c = 0; c <= MAX_CODE_POINT; c++) {
    if (!musl.iswalpha(c)) continue;
    if (ranges.length > 0 && ranges[ranges.length - 1] === c - 1)
      ranges[ranges.length - 1] = c;
    else ranges.push(c, c);
  }
  const lines: string[] = [];
  for (let i = 0; i < ranges.length; i += 16)
    lines.push(`  ${ranges.slice(i, i + 16).join(",")},`);
  const out = join(
    resolve(import.meta.dirname, "../.."),
    "src/core/musl-alpha.ts",
  );
  writeFileSync(
    out,
    `// Generated by wctype.node.ts from web-tree-sitter.wasm; do not edit. musl's iswalpha as sorted inclusive ranges.\nexport const MUSL_ALPHA = new Int32Array([\n${lines.join("\n")}\n]);\n`,
  );
  console.log(`${out}: ${ranges.length / 2} ranges`);
}

if (
  import.meta.url ===
  `file://${process.argv[1]?.replaceAll("\\", "/").replace(/^\/?/, "/")}`
)
  main();
