// Generated by src/gen-grammar.node.ts from tree-sitter-json 0.24.8. Do not edit.
export const grammar = {
  kinds: [
    "array",
    "comment",
    "document",
    "escape_sequence",
    "false",
    "null",
    "number",
    "object",
    "pair",
    "string",
    "string_content",
    "true",
  ],
  tokens: ['"', ",", ":", "[", "]", "{", "}"],
  fields: ["key", "value"],
  comments: ["comment"],
} as const;
