// TypeScript types (customs: print/types.ts).
import { custom, inOrder, space } from "../../../fmt/dsl/dsl.js";
import type { JsStructure } from "../format.js";

export const types = {
  literal_type: ($) => $.children,
  type_annotation: ($) => [":", space, $.children],
  opting_type_annotation: ($) => ["?:", space, $.children],
  omitting_type_annotation: ($) => ["-?:", space, $.children],
  adding_type_annotation: ($) => ["+?:", space, $.children],
  type_predicate_annotation: ($) => [":", space, $.children],
  asserts_annotation: ($) => [":", space, $.children],
  asserts: () => inOrder(space),
  type_predicate: ($) => [$.name, space, "is", space, $.type],
  array_type: ($) => [$.children, "[", "]"],
  lookup_type: () => inOrder(),
  optional_type: ($) => [$.children, "?"],
  rest_type: ($) => ["...", $.children],
  generic_type: ($) => [$.name, $.type_arguments],
  type_query: ($) => ["typeof", space, $.children],
  index_type_query: () => inOrder(space),
  readonly_type: () => inOrder(space),
  template_literal_type: () => inOrder(),
  template_type: ($) => ["${", $.children, "}"],
  enum_declaration: () => inOrder(space),
  parenthesized_type: () => custom("parenthesizedType"),
  infer_type: () => custom("inferType"),
  intersection_type: () => custom("intersectionType"),
  type_parameters: () => custom("typeParameters"),
  type_arguments: () => custom("typeParameters"),
  type_parameter: () => custom("typeParameter"),
  ambient_declaration: () => custom("ambientDeclaration"),
  as_expression: () => custom("castExpression"),
  satisfies_expression: () => custom("castExpression"),
} satisfies JsStructure;
