// TypeScript types (customs: print/types.ts).
import { custom, inOrder, space, tok } from "../../../fmt/dsl/dsl.js";
import type { JsStructure } from "../format.js";

export const types = {
  literal_type: ($) => $.children,
  type_annotation: ($) => [":", space, $.children],
  opting_type_annotation: ($) => ["?:", space, $.children],
  omitting_type_annotation: ($) => ["-?:", space, $.children],
  adding_type_annotation: ($) => ["+?:", space, $.children],
  type_predicate_annotation: ($) => [":", space, $.children],
  asserts_annotation: ($) => [":", space, $.children],
  asserts: () => inOrder(space),
  type_predicate: ($) => [$.name, space, "is", space, $.type],
  array_type: ($) => [$.children, "[", "]"],
  lookup_type: () => inOrder(),
  optional_type: ($) => [$.children, "?"],
  rest_type: ($) => ["...", $.children],
  generic_type: ($) => [$.name, $.type_arguments],
  type_query: ($) => ["typeof", space, $.children],
  index_type_query: () => inOrder(space),
  readonly_type: () => inOrder(space),
  template_literal_type: () => inOrder(),
  template_type: ($) => ["${", $.children, "}"],
  enum_declaration: () => inOrder(space),
  enum_assignment: ($) => [
    $.name.via("memberKey"),
    space,
    "=",
    space,
    $.value,
  ],
  module: ($) => [
    "module",
    space,
    $.name,
    $.body.andThen((b) => [space, b.via("moduleBody")]),
    tok(";").via("moduleSemi"),
  ],
  internal_module: ($) => [
    "namespace",
    space,
    $.name,
    $.body.andThen((b) => [space, b.via("moduleBody")]),
    tok(";").via("moduleSemi"),
  ],
  parenthesized_type: () => custom("parenthesizedType"),
  infer_type: () => custom("inferType"),
  union_type: () => custom("unionType"),
  tuple_type: () => custom("array"),
  intersection_type: () => custom("intersectionType"),
  type_parameters: () => custom("typeParameters"),
  type_arguments: () => custom("typeParameters"),
  type_parameter: () => custom("typeParameter"),
  ambient_declaration: () => custom("ambientDeclaration"),
  as_expression: () => custom("castExpression"),
  satisfies_expression: () => custom("castExpression"),
  object_type: () => custom("typeBody"),
  interface_body: () => custom("typeBody"),
  property_signature: ($) => [
    $.name.via("memberKey"),
    $.type.andThen((t) => t),
    tok(";").via("memberSemi"),
  ],
  method_signature: ($) => [
    $.name.via("methodSignature"),
    tok(";").via("memberSemi"),
  ],
  call_signature: ($) => [
    $.parameters.via("signature"),
    tok(";").via("memberSemi"),
  ],
  construct_signature: ($) => [
    $.parameters.via("signature"),
    tok(";").via("memberSemi"),
  ],
  function_type: () => custom("functionType"),
  constructor_type: () => custom("functionType"),
  index_signature: ($) => [
    $.type.via("indexSignature"),
    tok(";").via("memberSemi"),
  ],
} satisfies JsStructure;
