// Writes src/grammars/<name>/highlight.gen.ts for every grammar package that ships a queries/highlights.scm (next
// to its src/, fetched at the pinned commit like its other sources, see grammars/build.mjs). The highlighter is
// the query itself, parsed into data that ./index.ts runs; the only hand-written part is ./sitter-to-tm.ts.
// packages/syntechs/generate.mjs bundles this file with esbuild and runs it on every install, like the
// formatters' generator; the output is derived and untracked.
import { existsSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { GRAMMARS } from "../compiler/grammars.js";
import { createHighlighter } from "./index.js";
import { parseQuery } from "./query.js";

// Run as generate.mjs's bundle, dist/compiler/highlight-generate.mjs.
const pkg = resolve(import.meta.dirname, "../..");
const modules = join(pkg, "node_modules");

for (const [name, g] of Object.entries(GRAMMARS)) {
  const queryPath = join(dirname(g.src), "queries", "highlights.scm");
  const file = join(modules, queryPath);
  if (!existsSync(file)) continue;
  const root = g.src.split("/")[0] as string;
  const { version } = JSON.parse(
    readFileSync(join(modules, root, "package.json"), "utf8"),
  ) as { version: string };
  let patterns;
  try {
    patterns = parseQuery(readFileSync(file, "utf8"));
    // Every capture must have a TextMate scope (or be marked as none) before the module is written.
    createHighlighter(patterns, name);
  } catch (e) {
    throw new Error(`${file}: ${(e as Error).message}`);
  }
  const out = join(pkg, "src", "grammars", name, "highlight.gen.ts");
  writeFileSync(
    out,
    `// Generated by src/highlight/generate.node.ts from ${queryPath} (${version}); do not edit.
import { createHighlighter, type Highlighter, type Pattern } from "../../highlight/index.js";

const PATTERNS: Pattern[] = ${JSON.stringify(patterns)};

export const highlight: Highlighter = createHighlighter(PATTERNS, ${JSON.stringify(name)});
`,
  );
  console.log(`wrote ${out} (${patterns.length} patterns)`);
}
